//
//  LSIContactController.m
//  Contacts-Hybrid
//
//  Created by Paul Solt on 12/16/19.
//  Copyright © 2019 Lambda, Inc. All rights reserved.
//

#import "LSIContactController.h"


// Rule Swift->Objective-C: always put this import in the .m file (not the header)
// otherwise you'll have build cycle issues and strange build failures
#import "Contacts_Hybrid-Swift.h" // autogenerated file always of the form "ProjectName-Swift.h"

@implementation LSIContactController

- (instancetype)init {
	self = [super init];
	if (self) {
		// Allocation: Buy the land
		// Initializer: building the house
		
		// Create our data from Swift objects in Objective-C
		Contact *paul = [[Contact alloc] initWithName:@"Paul" relationship:@"Myself"];
		Contact *steph = [[Contact alloc] initWithName:@"Steph" relationship:@"Wife"];
		
		_contacts = @[paul, steph]; // [NSArray arrayWithObjects:paul, steph, nil];
//		_contacts = @[paul, steph, @"Bob"]; // Currently NSArray can store any type, making this bad data
	}
	return self;
}


@end
